# Generated by Django 5.0 on 2026-01-27 01:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Ativo'), ('INACTIVE', 'Inativo'), ('SUSPENDED', 'Suspenso')], default='ACTIVE', max_length=20)),
                ('plan', models.CharField(choices=[('BASIC', 'Básico'), ('STANDARD', 'Padrão'), ('PREMIUM', 'Premium')], default='BASIC', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
                'db_table': 'cities',
                'ordering': ['-created_at'],
            },
        ),
    ]
