# Generated by Django 5.2.7 on 2026-03-02 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0003_camera_timezone'),
        ('deteccoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LPRDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_text', models.CharField(db_index=True, max_length=20)),
                ('confidence', models.FloatField()),
                ('bbox', models.JSONField()),
                ('plate_id', models.CharField(max_length=50)),
                ('plate_image_path', models.CharField(max_length=500)),
                ('full_frame_path', models.CharField(max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_mercosul', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.RenameIndex(
            model_name='deteccao',
            new_name='deteccoes_d_camera__bd3486_idx',
            old_name='deteccoes_d_camera__idx',
        ),
        migrations.RenameIndex(
            model_name='deteccao',
            new_name='deteccoes_d_placa_ca1e84_idx',
            old_name='deteccoes_d_placa_idx',
        ),
        migrations.AddField(
            model_name='lprdetection',
            name='camera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lpr_detections', to='cameras.camera'),
        ),
        migrations.AddIndex(
            model_name='lprdetection',
            index=models.Index(fields=['-timestamp', 'camera'], name='deteccoes_l_timesta_c51ec5_idx'),
        ),
        migrations.AddIndex(
            model_name='lprdetection',
            index=models.Index(fields=['plate_text'], name='deteccoes_l_plate_t_685bc0_idx'),
        ),
    ]
