# Generated by Django 5.2.7 on 2025-11-06 13:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cameras", "0003_alter_camera_detection_settings"),
        ("deteccoes", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="deteccao",
            index=models.Index(
                fields=["camera", "-timestamp"], name="deteccoes_d_camera__b6d6d1_idx"
            ),
        ),
    ]
