# Generated by Django 5.2.7 on 2026-03-22 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0004_add_stream_key_brand_model'),
        ('deteccoes', '0002_lprdetection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lprdetection',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='lprdetection',
            name='device_id',
            field=models.CharField(blank=True, default='', help_text='ID do dispositivo que enviou', max_length=100),
        ),
        migrations.AddField(
            model_name='lprdetection',
            name='direction',
            field=models.CharField(blank=True, default='', help_text='Direcao do veiculo', max_length=20),
        ),
        migrations.AddField(
            model_name='lprdetection',
            name='trigger_source',
            field=models.CharField(blank=True, default='', help_text='Fonte do disparo', max_length=50),
        ),
        migrations.AddField(
            model_name='lprdetection',
            name='vehicle_brand',
            field=models.CharField(blank=True, default='', help_text='Marca do veiculo (Toyota, Ford...)', max_length=50),
        ),
        migrations.AddField(
            model_name='lprdetection',
            name='vehicle_color',
            field=models.CharField(blank=True, default='', help_text='Cor do veiculo', max_length=30),
        ),
        migrations.AddField(
            model_name='lprdetection',
            name='vehicle_model',
            field=models.CharField(blank=True, default='', help_text='Modelo (Corolla, Ka...)', max_length=100),
        ),
        migrations.AddField(
            model_name='lprdetection',
            name='vehicle_type',
            field=models.CharField(choices=[('car', 'Automovel'), ('motorcycle', 'Motocicleta'), ('truck', 'Caminhao'), ('bus', 'Onibus'), ('van', 'Van'), ('utility', 'Utilitario'), ('unknown', 'Desconhecido')], default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='lprdetection',
            name='vehicle_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lprdetection',
            name='bbox',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='lprdetection',
            name='full_frame_path',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='lprdetection',
            name='plate_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='lprdetection',
            name='plate_image_path',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddIndex(
            model_name='lprdetection',
            index=models.Index(fields=['vehicle_brand'], name='deteccoes_l_vehicle_ac9f3e_idx'),
        ),
    ]
