# Generated by Django 5.2.7 on 2026-03-23 02:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deteccoes', '0003_add_vehicle_fields_webhook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lprdetection',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
