# Generated by Django 5.2.7 on 2026-03-23 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0007_add_device_id'),
        ('deteccoes', '0004_change_timestamp_default'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='lprdetection',
            constraint=models.UniqueConstraint(fields=('camera', 'plate_text', 'timestamp'), name='unique_detection_per_camera'),
        ),
    ]
