# Generated by Django 5.2.7 on 2026-03-02 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_remove_unused_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='loginlog',
            new_name='login_logs_user_id_b34af7_idx',
            old_name='login_logs_user_id_c51ec5_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationlog',
            new_name='notificatio_user_id_dd1554_idx',
            old_name='notificati_user_id_8b2ede_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationlog',
            new_name='notificatio_categor_012630_idx',
            old_name='notificati_categor_f6deca_idx',
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='category',
            field=models.CharField(choices=[('camera_offline', 'Câmera Offline'), ('system', 'Sistema')], max_length=50, verbose_name='Categoria'),
        ),
    ]
