# Generated by Django 5.2.7 on 2026-03-02 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0002_clip_protection'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='clip',
            new_name='clips_clip_owner_i_5d3ba2_idx',
            old_name='clips_clip_owner_created_idx',
        ),
        migrations.RenameIndex(
            model_name='clip',
            new_name='clips_clip_externa_5e2842_idx',
            old_name='clips_clip_external_idx',
        ),
        migrations.RenameIndex(
            model_name='clip',
            new_name='clips_clip_is_prot_58eaf1_idx',
            old_name='clips_clip_protected_idx',
        ),
    ]
