# Generated by Django 5.2.7 on 2026-03-02 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='tenantisolation',
            new_name='iam_tenanti_user_id_8b2ede_idx',
            old_name='iam_tenanti_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='tenantisolation',
            new_name='iam_tenanti_resourc_f6deca_idx',
            old_name='iam_tenanti_resourc_idx',
        ),
    ]
