# Generated by Django 5.2.7 on 2025-11-04 05:12

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConfiguracaoGlobal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notificacoes_habilitadas",
                    models.BooleanField(
                        default=True,
                        help_text="Habilita/desabilita todas as notificações do sistema.",
                    ),
                ),
                (
                    "email_suporte",
                    models.EmailField(
                        blank=True,
                        help_text="Email para onde as solicitações de suporte são enviadas.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "em_manutencao",
                    models.BooleanField(
                        default=False,
                        help_text="Coloca o sistema em modo de manutenção.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Configuração Global",
                "verbose_name_plural": "Configurações Globais",
            },
        )
    ]
