# Generated by Django 5.2.7 on 2026-03-22 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0003_camera_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='brand',
            field=models.CharField(blank=True, help_text='Marca da camera (hikvision, intelbras)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='model_name',
            field=models.CharField(blank=True, help_text='Modelo da camera', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='stream_key',
            field=models.CharField(blank=True, help_text='Chave unica para RTMP push', max_length=32, null=True, unique=True),
        ),
    ]
