# Generated by Django 5.2.7 on 2026-03-23 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0004_add_stream_key_brand_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='camera',
            name='stream_url',
            field=models.CharField(max_length=1000),
        ),
    ]
