# Generated by Django 5.2.7 on 2026-03-23 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0005_remove_unique_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='stream_key',
            field=models.CharField(blank=True, help_text='Chave unica para RTMP push ou DeviceID', max_length=64, null=True, unique=True),
        ),
    ]
