# Generated by Django 5.2.7 on 2026-03-23 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0006_increase_stream_key_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='device_id',
            field=models.CharField(blank=True, help_text='DeviceID da camera para webhook push', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='stream_key',
            field=models.CharField(blank=True, help_text='Chave unica para RTMP push', max_length=32, null=True, unique=True),
        ),
    ]
