# Generated by Django 5.0 on 2026-01-27 01:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cidades', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('stream_url', models.CharField(max_length=512)),
                ('protocol', models.CharField(choices=[('RTSP', 'RTSP'), ('RTMP', 'RTMP')], max_length=10)),
                ('is_lpr', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='cidades.city')),
            ],
            options={
                'verbose_name': 'Câmera',
                'verbose_name_plural': 'Câmeras',
                'db_table': 'cameras',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['city', 'is_active'], name='cameras_city_id_283a66_idx'), models.Index(fields=['public_id'], name='cameras_public__6cf910_idx')],
                'unique_together': {('city', 'name')},
            },
        ),
    ]
