# Generated by Django 5.0 on 2026-01-27 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='camera',
            options={'ordering': ['-created_at'], 'permissions': [('view_own_city_cameras', 'Can view cameras from own city only'), ('manage_own_city_cameras', 'Can manage cameras from own city only'), ('view_all_cameras', 'Can view all cameras (superadmin)')], 'verbose_name': 'Câmera', 'verbose_name_plural': 'Câmeras'},
        ),
    ]
