# Generated by Django 5.0 on 2026-01-27 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0002_alter_camera_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='camera',
            options={'ordering': ['-created_at'], 'permissions': [('view_city_cameras', 'Can view cameras from own city'), ('manage_city_cameras', 'Can manage cameras from own city')], 'verbose_name': 'Câmera', 'verbose_name_plural': 'Câmeras'},
        ),
    ]
