# Generated by Django 5.0 on 2026-01-27 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0003_alter_camera_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='recording_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
